@host = http://localhost:3000/api
@user_email = kimo@gmail.com
@user_password = KimoOmar
@admin_email = admin@gmail.com
@admin_password = admin

############################################################################
# ============================ Create new User ============================
POST {{ host }}/auth/register
Content-Type: application/json

{
    "username": "Admin",
    "email": "admin@gmail.com",
    "password": "admin"
}

############################################################################
# ============================ Login with email ============================
# @name login

POST {{ host }}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "{{admin_email}}",
    "password": "{{admin_password}}"
}


############################################################################
# ============================ Go into Home ============================
@token = {{ login.response.body.token }}

GET {{ host }}/home/welcome
Content-Type: application/json
Authorization: Bearer {{token}}

############################################################################
# ============================ Go into Dashboard ============================
GET {{ host }}/admin/dashboard
Content-Type: application/json
Authorization: Bearer {{token}}


############################################################################
# ============================ Add new Image  [use postman simpler] ============================
POST {{ host }}/images
Authorization: Bearer {{token}}

image=@./images/photo.jpg

############################################################################
# ============================ Get Images ============================
GET {{ host }}/images